#!/usr/bin/env bash
# gpgcreds
# A git credential helper to store git credentials encrypted on disk
set -euo pipefail

HELP_MSG=$(cat <<-E_HELP_MSG
    USAGE: gpgcreds
           A git credential helper to store git credentials encrypted on disk
    COMMANDS
           store:      Save git credentials into the gpg encrypted file.
           get:        Print credentials to STDOUT for parameters from STDIN.
           namespace:  Print active namespace to use.
    
           NOT YET IMPLEMENTED:
           erase:  Remove git credentials from the file store for the given parameters.
           accept:  Save git credentials into the gpg encrypted file.

    COMMAND PARAMETERS:
        url:       Form: '{protocol}://{host}'  (e.g., 'https://github.com')
        protocol:  URL protocol (e.g., 'https')
        host:      URL host (e.g., 'github.com')
        username:  git account username
        password:  git account password or personal access token

        Note: git credentials helper parameters are read from STDIN.
        
    COMMAND REQUIREMENTS
        store:  Requires all parameters to specified; 'url' may be used in place of 'protocol' and 'host'.
        get:   Requires only 'protocol' and 'host' to be specified; 'url' may be used in place of 'protocol' and 'host'.

    NAMESPACE
        gpgcreds will use \$(git config credential.namespace) to determine the namespace prefix of a gpgcreds file store.

    CREDENTIAL STORE
        Uses "~/.config/gpgcreds/{namespace}.gpgcreds.cyp' as the location for the credential file store.

    REFERENCE
        git credential store
        https://git-scm.com/docs/git-credential
        https://git-scm.com/doc/credential-helpers
        https://git-scm.com/docs/git-credential-store
E_HELP_MSG
)


# UTILITY FUNCTIONS
read_params() {
    # Read credentials parameters from STDIN and then generate a formatted string
    local -n d_creds=$1
    while IFS=$'\r\n' read -r line; do
        if [[ -z "$line" ]]; then
            break;
        fi
        # readarray -d '=' -t raw_attrs < <(printf "%s" "$line")
        if [[ "${line}" =~ ^([^=]+)=(.*) ]]; then
            attrs=(${BASH_REMATCH[1]} ${BASH_REMATCH[2]})
        fi
        # Trim out stuff that we don't use
        # mod_key=$(tr -d '[]' ${attrs[0]})
        # attrs=("${mod_key}" "${attrs[1]}")
        # echo "(D): attrs='${attrs[@]}'" >&2;
        case "${attrs[0]}" in
            url)
                d_creds[url]="${attrs[1]}";
                ;;
            protocol)
                d_creds[protocol]="${attrs[1]}";
                ;;
            host)
                d_creds[host]="${attrs[1]}";
                ;;
            username)
                d_creds[username]="${attrs[1]}";
                ;;
            password)
                d_creds[password]="${attrs[1]}";
                ;;
            path | "capability[]" | "wwwauth[]" | "state[]" | continue  | ephemeral | credential | authtype | oauth_refresh_token | password_expiry_utc)
                echo "(W): Skipping unsupported git attribute: '${attrs[0]}'." >&2;
                ;;
            *)
                echo "(E): Unrecognized git attribute '${attrs[0]}'." >&2;
                exit 1;
        esac
    done
}

read_params_dumb() {
    echo 'quit=true'
    while read -r line; do
        echo "(D): LINE='${line}'" >&2;
    done
}

check_creds() {
    local -n __creds=$1;
    [[ \
        ( (-n "${__creds[protocol]}" && -n "${__creds[host]}" ) || -n "${__creds[url]}" ) \
        && -n "${__creds[username]}" \
        && -n "${__creds[password]}" \
    ]];
}

format_creds() {
    # Generate a formatted string of the given credentials
    # Arguments:
    #     $1 : Dictionary of credentials from read_params()
    #     $1 : Variable for formatted string
    local -n _creds=$1;
    local -n _fmt_creds=$2;
    if check_creds _creds; then
        if [[ -n "${_creds[protocol]}" && -n "${_creds[host]}" ]]; then
            _fmt_creds="${_creds[protocol]}://${_creds[username]}:${_creds[password]}@${_creds[host]}";
        elif [[ -n "${_creds[url]}" ]]; then
            _fmt_creds="${_creds[url]/:\/\//:\/\/${_creds[username]}:${_creds[password]}@}";
        fi
    else
        echo "(E): Missing required git credentials attributes. See '-h' for usage." >&2;
        exit 22;
    fi
}


# MAIN
if [[ "$1" == '-h' || "$1" == '--help' ]]; then
    echo "$HELP_MSG";
    exit 0;
fi
if [[ -z "$1" ]]; then
    echo "(E): Command required: Use -h for available commands." >&2;
    exit 1;
fi

DEFAULT_CREDS_DIR="$HOME/.config/gpgcreds";
DEFAULT_PREFIX='primary';
if [[ ! -e "$DEFAULT_CREDS_DIR" ]]; then
    mkdir -p "$DEFAULT_CREDS_DIR";
    mk_rc=$?
    if [[ $mk_rc -ne 0 ]]; then
        echo "(E):  Unable to create directory '$DEFAULT_CREDS_DIR'." >&2;
        exit $mk_rc;
    fi
elif [[ ! -d "$DEFAULT_CREDS_DIR" ]]; then
    echo "(E): '$DEFAULT_CREDS_DIR' is not a directory." >&2;
    exit 2;
fi

STORE_PREFIX=$(git config credential.namespace);
if [[ -n "$STORE_PREFIX" ]]; then
    GPGCREDS_STORE="$DEFAULT_CREDS_DIR/${STORE_PREFIX}.gpgcreds.cyp";
else
    GPGCREDS_STORE="$DEFAULT_CREDS_DIR/${DEFAULT_PREFIX}.gpgcreds.cyp";
fi
if [[ ! "${STORE_PREFIX}" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    echo "(E): Invalid namespace. See '-h' for usage." >&2;
fi

declare -A git_creds;
declare fmt_creds;
case "$1" in
    namespace)
        echo "Namespace: '${STORE_PREFIX}'";
        echo "Path:      '${GPGCREDS_STORE}'";
        exit 0;
    ;;
    accept | store)
        read_params git_creds;
        format_creds git_creds fmt_creds;
        gpg_key=$(git config user.signingkey);
        if [[ -z "${gpg_key}" ]]; then
            echo "(E): Missing git config user.signingkey.";
            exit 22;
        fi
        if ! gpg --list-keys "${gpg_key}" &>/dev/null; then
            echo "(E): GPG Key '${gpg_key}' not found in keyring." >&2;
            exit 1;
        fi
        # gpg --recipient "${gpg_key}" -e > "${GPGCREDS_STORE}" < <(printf "%s\n" "${fmt_creds}");
        gpg --recipient "${gpg_key}" -e > "${GPGCREDS_STORE}" <<< "${fmt_creds}";
        exit 0;
    ;;
    get | fill)
        echo 'quit=true'
        URL_RE='^([a-zA-Z0-9+.-]+)://(.*)';
        read_params git_creds;
        declare -A search_creds;
        if [[ -n "${git_creds[protocol]}" && -n "${git_creds[host]}" ]]; then
            search_creds[protocol]=${git_creds[protocol]}
            search_creds[host]=${git_creds[host]}
        elif [[ -n "${git_creds[url]}" ]]; then
            if [[ "${git_creds[url]}" =~ $URL_RE ]]; then
                search_creds[protocol]="${BASH_REMATCH[1]}"
                search_creds[host]="${BASH_REMATCH[2]}"
            else
                echo "(E): Malformed url."
                exit 22;
            fi
        else
            echo "(E): Missing required git credential attributes. See '-h' for usage." >&2;
            exit 22;
        fi

        # Validate user input used in REGEX matches
        if [[ ! "${search_creds[protocol]}" =~ ^[a-zA-Z][a-zA-Z0-9+.-]*$ ]]; then
            echo "(E): Invalid URI protocol format." >&2;
            exit 22;
        fi
        # Check for valid hostnames, which may include '.'
        if [[ ! "${search_creds[host]}" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?)*$ ]]; then
            echo "(E): Invalid URI protocol format." >&2;
            exit 22;
        fi

        declare -A match_creds;
        gpg_grep_rc=1
        while read -r line; do
            # if [[ "${line}" =~ ^${search_creds[protocol]}://(([^:@]+)(:([^@]+))?@)?${search_creds[host]}$ ]]; then
            if [[ "${line}" =~ ^${search_creds[protocol]}://([^:@]+):?(.*)@${search_creds[host]}$ ]]; then
                gpg_grep_rc=$?;
                match_creds[username]="${BASH_REMATCH[1]}";
                match_creds[password]="${BASH_REMATCH[2]}";
                # echo "${line}";
                echo "quit=true";
                echo "username=${match_creds[username]}"
                echo "password=${match_creds[password]}"
                break;
            fi
        done < <(gpg -dq "${GPGCREDS_STORE}")
        gpg_grep_rc=$gpg_grep_rc || $?;
        if [[ $gpg_grep_rc -ne 0 ]]; then
            echo "(E):  Unable to decrypt GPG credential store file with matching git attributes." >&2;
            exit $gpg_grep_rc;
        fi
        exit 0;
        ;;
    *)
        echo "Unrecognized command '$1'. Use -h for available commands." >&2;
        exit 1;
        ;;
esac
